// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3ILYUYvYT6URkBPOVIS74io5ET0cOOQ',
    appId: '1:70756738260:web:a1fd7ba8be847dd8778741',
    messagingSenderId: '70756738260',
    projectId: 'pawvault-e0cc5',
    authDomain: 'pawvault-e0cc5.firebaseapp.com',
    storageBucket: 'pawvault-e0cc5.firebasestorage.app',
    measurementId: 'G-6P3CBX2P67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnq9sx2OYrF-KDJU4I_lbLrIxBM-u8mZI',
    appId: '1:70756738260:android:495fdafa3fee8749778741',
    messagingSenderId: '70756738260',
    projectId: 'pawvault-e0cc5',
    storageBucket: 'pawvault-e0cc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfewE7NY0xThytX2ejHwZZrh4EP7u21Wk',
    appId: '1:70756738260:ios:6cb7a40554b8337d778741',
    messagingSenderId: '70756738260',
    projectId: 'pawvault-e0cc5',
    storageBucket: 'pawvault-e0cc5.firebasestorage.app',
    iosClientId: '70756738260-0h6apq6uau16rut6242q4m60t4vjs8rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfewE7NY0xThytX2ejHwZZrh4EP7u21Wk',
    appId: '1:70756738260:ios:6cb7a40554b8337d778741',
    messagingSenderId: '70756738260',
    projectId: 'pawvault-e0cc5',
    storageBucket: 'pawvault-e0cc5.firebasestorage.app',
    iosClientId: '70756738260-0h6apq6uau16rut6242q4m60t4vjs8rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX3ILYUYvYT6URkBPOVIS74io5ET0cOOQ',
    appId: '1:70756738260:web:240dd32429993d5d778741',
    messagingSenderId: '70756738260',
    projectId: 'pawvault-e0cc5',
    authDomain: 'pawvault-e0cc5.firebaseapp.com',
    storageBucket: 'pawvault-e0cc5.firebasestorage.app',
    measurementId: 'G-BDF4432S0G',
  );

}